include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
    avoid_print: true
    use_key_in_widget_constructors: true
    prefer_relative_imports: false
    always_declare_return_types: true
